cell_formats\demo_write_formatting -quit
colors\demo_write_colors -quit
conditional_formatting\demo_conditional_formatting -quit
defined_names\demo_write_definednames -quit
expression_parser\demo_expression_parser -quit
frozen_rowscols\demo_frozen_rows_cols -quit
header_footer_images\demo_write_headerfooter_images -quit
hyperlinkdemo\collectlinks -quit
ignore_formulas\demo_ignore_formula -quit
images\demo_write_images -quit
metadata\demo_metadata -quit
pagelayout\demo_pagelayout -quit
protection\demo_protection -quit
recursive_calculation\demo_recursive_calc -quit
richtext\demo_richtext_utf8 -quit
rpn_formulas\demo_write_formula -quit
searching\demo_search -quit
sorting\demo_sorting -quit
user_defined_formulas\demo_formula_func -quit
virtual_mode\demo_virtualmode_write -quit
virtual_mode\demo_virtualmode_read -quit
